# Generated by Django 5.2.16 on 2026-08-07 08:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=250)),
                ('konum', models.CharField(max_length=250)),
                ('fiyat', models.DecimalField(decimal_places=2, max_digits=12)),
                ('ilan_tarihi', models.DateField(blank=True, null=True)),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('guncellenme_tarihi', models.DateTimeField(auto_now_add=True)),
                ('sahibi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ilanlar', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-olusturulma_tarihi'],
            },
        ),
        migrations.CreateModel(
            name='CarListing',
            fields=[
                ('listing_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='listings.listing')),
                ('marka', models.CharField(max_length=100)),
                ('seri', models.CharField(blank=True, max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('yil', models.PositiveIntegerField(blank=True, null=True)),
                ('kilometre', models.PositiveIntegerField(blank=True, null=True)),
                ('vites_tipi', models.CharField(blank=True, choices=[('manuel', 'Manuel'), ('otomatik', 'Otomatik'), ('yari_otomatik', 'Yarı otomatik')], max_length=20)),
                ('yakit_tipi', models.CharField(blank=True, max_length=50)),
                ('kasa_tipi', models.CharField(blank=True, max_length=50)),
                ('renk', models.CharField(blank=True, max_length=50)),
                ('motor_hacmi', models.CharField(blank=True, max_length=50)),
                ('motor_gucu', models.CharField(blank=True, max_length=50)),
                ('cekis', models.CharField(blank=True, max_length=50)),
                ('arac_durumu', models.CharField(blank=True, max_length=100)),
                ('ortalama_yakit_tuketimi', models.CharField(blank=True, max_length=50)),
                ('yakit_deposu', models.CharField(blank=True, max_length=50)),
                ('boya_degisen', models.CharField(blank=True, max_length=100)),
                ('takasa_uygun', models.BooleanField(blank=True, null=True)),
                ('kimden', models.CharField(blank=True, max_length=50)),
                ('tramer', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
            ],
            options={
                'verbose_name': 'Araç İlanı',
                'verbose_name_plural': 'Araç İlanları',
            },
            bases=('listings.listing',),
        ),
        migrations.CreateModel(
            name='HouseListing',
            fields=[
                ('listing_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='listings.listing')),
                ('metrekare', models.PositiveIntegerField(blank=True, null=True)),
                ('bina_yasi', models.CharField(blank=True, max_length=50)),
                ('toplam_kat_sayisi', models.PositiveIntegerField(blank=True, null=True)),
                ('oda_sayisi', models.CharField(blank=True, max_length=20)),
                ('bulundugu_kat', models.CharField(blank=True, max_length=20)),
                ('kredi_uygunlugu', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Ev İlanı',
                'verbose_name_plural': 'Ev İlanları',
            },
            bases=('listings.listing',),
        ),
    ]
