# Generated by Django 5.2.17 on 2026-08-10 08:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listing',
            options={'ordering': ['-listing_date']},
        ),
        migrations.RemoveField(
            model_name='carlisting',
            name='arac_durumu',
        ),
        migrations.RemoveField(
            model_name='carlisting',
            name='boya_degisen',
        ),
        migrations.RemoveField(
            model_name='carlisting',
            name='cekis',
        ),
        migrations.RemoveField(
            model_name='carlisting',
            name='kasa_tipi',
        ),
        migrations.RemoveField(
            model_name='carlisting',
            name='kilometre',
        ),
        migrations.RemoveField(
            model_name='carlisting',
            name='kimden',
        ),
        migrations.RemoveField(
            model_name='carlisting',
            name='marka',
        ),
        migrations.RemoveField(
            model_name='carlisting',
            name='motor_gucu',
        ),
        migrations.RemoveField(
            model_name='carlisting',
            name='motor_hacmi',
        ),
        migrations.RemoveField(
            model_name='carlisting',
            name='ortalama_yakit_tuketimi',
        ),
        migrations.RemoveField(
            model_name='carlisting',
            name='renk',
        ),
        migrations.RemoveField(
            model_name='carlisting',
            name='seri',
        ),
        migrations.RemoveField(
            model_name='carlisting',
            name='takasa_uygun',
        ),
        migrations.RemoveField(
            model_name='carlisting',
            name='vites_tipi',
        ),
        migrations.RemoveField(
            model_name='carlisting',
            name='yakit_deposu',
        ),
        migrations.RemoveField(
            model_name='carlisting',
            name='yakit_tipi',
        ),
        migrations.RemoveField(
            model_name='carlisting',
            name='yil',
        ),
        migrations.RemoveField(
            model_name='houselisting',
            name='bina_yasi',
        ),
        migrations.RemoveField(
            model_name='houselisting',
            name='bulundugu_kat',
        ),
        migrations.RemoveField(
            model_name='houselisting',
            name='kredi_uygunlugu',
        ),
        migrations.RemoveField(
            model_name='houselisting',
            name='metrekare',
        ),
        migrations.RemoveField(
            model_name='houselisting',
            name='oda_sayisi',
        ),
        migrations.RemoveField(
            model_name='houselisting',
            name='toplam_kat_sayisi',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='baslik',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='fiyat',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='guncellenme_tarihi',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='ilan_tarihi',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='konum',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='olusturulma_tarihi',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='sahibi',
        ),
        migrations.AddField(
            model_name='carlisting',
            name='avg_fuel_consumption',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='carlisting',
            name='body_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='carlisting',
            name='brand',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='carlisting',
            name='changed_parts',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='carlisting',
            name='color',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='carlisting',
            name='engine_power',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='carlisting',
            name='engine_size',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='carlisting',
            name='for_trade',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carlisting',
            name='from_whom',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='carlisting',
            name='fuel_tank',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='carlisting',
            name='fuel_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='carlisting',
            name='km',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carlisting',
            name='series',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='carlisting',
            name='status',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='carlisting',
            name='traction',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='carlisting',
            name='transmission_type',
            field=models.CharField(blank=True, choices=[('manueş', 'Manuel'), ('otomatik', 'Otomatik'), ('yarı otomatik', 'Yarı Otomatik')], max_length=20),
        ),
        migrations.AddField(
            model_name='carlisting',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='houselisting',
            name='building_aged',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='houselisting',
            name='credit_eligibility',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='houselisting',
            name='floor',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='houselisting',
            name='meter_squared',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='houselisting',
            name='number_of_floors',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='houselisting',
            name='number_of_rooms',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='listing',
            name='listing_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='listing_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ilanlar', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='listing',
            name='listing_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='location',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='listing',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='listing',
            name='title',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='carlisting',
            name='model',
            field=models.CharField(default='', max_length=100),
        ),
    ]
