# Generated by Django 5.2.17 on 2026-08-13 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_listing_city_listing_district'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='location',
        ),
    ]
