# Generated by Django 5.2.17 on 2026-08-16 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_remove_listing_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carlisting',
            name='transmission_type',
            field=models.CharField(blank=True, choices=[('manuel', 'Manuel'), ('otomatik', 'Otomatik'), ('yarı otomatik', 'Yarı Otomatik')], max_length=20),
        ),
        migrations.AlterField(
            model_name='listing',
            name='city',
            field=models.CharField(blank=True, db_index=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='listing',
            name='district',
            field=models.CharField(blank=True, db_index=True, default='', max_length=250),
        ),
    ]
