# Generated by Django 5.2.17 on 2026-08-10 12:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=250)),
                ('location', models.CharField(default='', max_length=250)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('listing_date', models.DateField(blank=True, null=True)),
                ('listing_update', models.DateTimeField(auto_now=True)),
                ('listing_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ilanlar', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-listing_date'],
            },
        ),
        migrations.CreateModel(
            name='CarListing',
            fields=[
                ('listing_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='listings.listing')),
                ('brand', models.CharField(default='', max_length=100)),
                ('series', models.CharField(blank=True, max_length=100)),
                ('model', models.CharField(default='', max_length=100)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('km', models.PositiveIntegerField(blank=True, null=True)),
                ('transmission_type', models.CharField(blank=True, choices=[('manueş', 'Manuel'), ('otomatik', 'Otomatik'), ('yarı otomatik', 'Yarı Otomatik')], max_length=20)),
                ('fuel_type', models.CharField(blank=True, max_length=50)),
                ('body_type', models.CharField(blank=True, max_length=50)),
                ('color', models.CharField(blank=True, max_length=50)),
                ('engine_size', models.CharField(blank=True, max_length=50)),
                ('engine_power', models.CharField(blank=True, max_length=50)),
                ('traction', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(blank=True, max_length=100)),
                ('avg_fuel_consumption', models.CharField(blank=True, max_length=50)),
                ('fuel_tank', models.CharField(blank=True, max_length=50)),
                ('changed_parts', models.CharField(blank=True, max_length=100)),
                ('for_trade', models.BooleanField(blank=True, null=True)),
                ('from_whom', models.CharField(blank=True, max_length=50)),
                ('tramer', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
            ],
            options={
                'verbose_name': 'Araç İlanı',
                'verbose_name_plural': 'Araç İlanları',
            },
            bases=('listings.listing',),
        ),
        migrations.CreateModel(
            name='HouseListing',
            fields=[
                ('listing_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='listings.listing')),
                ('meter_squared', models.PositiveIntegerField(blank=True, null=True)),
                ('building_aged', models.CharField(blank=True, max_length=50)),
                ('number_of_floors', models.PositiveIntegerField(blank=True, null=True)),
                ('number_of_rooms', models.CharField(blank=True, max_length=20)),
                ('floor', models.CharField(blank=True, max_length=20)),
                ('credit_eligibility', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Ev İlanı',
                'verbose_name_plural': 'Ev İlanları',
            },
            bases=('listings.listing',),
        ),
    ]
