# Generated by Django 5.2.17 on 2026-08-13 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_alter_listing_listing_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='city',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AddField(
            model_name='listing',
            name='district',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
    ]
