# Generated by Django 5.2.17 on 2026-08-25 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0012_alter_alarm_options_alarm_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarm',
            name='alarm_type',
            field=models.CharField(choices=[('new_listing_check', 'Yeni ilan kontrolü'), ('price_drop', 'Fiyat düşüşü'), ('favorite_updated', 'Favori güncellendi'), ('favorite_removed', 'Favori kaldirildi')], max_length=50),
        ),
    ]
