# Generated by Django 5.2.17 on 2026-08-25 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0013_alter_alarm_alarm_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='new_price',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='old_price',
        ),
        migrations.AlterField(
            model_name='alarm',
            name='alarm_type',
            field=models.CharField(choices=[('new_listing_check', 'Yeni ilan kontrolü'), ('price_change', 'Fiyat değişimi'), ('favorite_updated', 'Favori güncellendi'), ('favorite_removed', 'Favori kaldirildi')], max_length=50),
        ),
        migrations.AlterField(
            model_name='notification',
            name='listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='listings.listing'),
        ),
    ]
