# Generated by Django 5.2.17 on 2026-08-26 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0014_remove_notification_new_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='alarm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='listings.alarm'),
        ),
    ]
